"""Interface de repositório — o contrato que `Store` (in-memory) e `SqlStore`
(SQL) implementam, e do qual economia/temporada/`World` dependem.

Mantém o motor desacoplado do armazenamento: trocar in-memory por Postgres é
trocar a implementação, sem tocar nas regras.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

from ..engine.market_gen import MarketPlayer
from .models import Club, LedgerEntry

if TYPE_CHECKING:
    from ..domain.lineup import Lineup
    from .season import SeasonState


class Repository(Protocol):
    # ids
    def next_club_id(self) -> str: ...
    def next_txn_id(self) -> str: ...

    # clubes
    def add_club(self, club: Club) -> None: ...
    def get_club(self, club_id: str) -> Club | None: ...
    def get_user_club(self, user_id: str) -> str | None: ...
    def save_club(self, club: Club) -> None: ...

    # jogadores / mercado
    def load_market(self, mercado: list[MarketPlayer]) -> None: ...
    def is_empty(self) -> bool: ...
    def get_player(self, player_id: str) -> MarketPlayer | None: ...
    def update_player(self, mp: MarketPlayer) -> None: ...
    def owner_of(self, player_id: str) -> str | None: ...
    def set_owner(self, player_id: str, club_id: str) -> None: ...
    def elenco(self, club_id: str) -> list[str]: ...
    def available_market(self) -> list[MarketPlayer]: ...

    # ledger
    def post_ledger(self, club: Club, tipo: str, valor_fvs: int,
                    ref: str | None = None, criado_em: str | None = None) -> LedgerEntry: ...
    def ledger_balance(self, club_id: str) -> int: ...
    def get_ledger(self, club_id: str) -> list[LedgerEntry]: ...

    # temporada (estado transitório entre rodadas)
    def save_season(self, season: SeasonState) -> None: ...
    def get_season(self, club_id: str) -> SeasonState | None: ...

    # escalação ativa
    def save_lineup(self, club_id: str, lineup: Lineup) -> None: ...
    def get_lineup(self, club_id: str) -> Lineup | None: ...
    def delete_lineup(self, club_id: str) -> None: ...
